name: flutter_highlight
description: Flutter syntax highlighter with lots of languages and styles support. Zero dependencies, automatic language detection.
version: 0.2.1
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/highlight

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   highlight:
#     path: ../highlight

flutter:
