name: highlight
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/highlight

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.6.5
  json_serializable: ^3.2.0
